version: 1.0.{build}
image:
- Ubuntu

environment:
  global:
    USER: sumankhanal
  matrix:
    - RAKU_VERSION: daily
    - RAKU_VERSION: 2020.06
    - RAKU_VERSION: 2020.07
    - RAKU_VERSION: 2020.08.2
    - RAKU_VERSION: 2020.09

build_script:
  - ps: ./build.ps1

deploy_script:
  - ps: ./deploy.ps1