sudo: required

services:
  - docker

env:
  matrix:
    - RAKU_VER=daily
    - RAKU_VER=2019.07.1
    - RAKU_VER=2019.11


before_install:
  - docker build -t sumankhanal/rakudo:{RAKU_VER} ${RAKU_VER}
  

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sumankhanal/rakudo:${RAKU_VER}