sudo: required

services:
  - docker

env:
  global:
    - USER=sumankhanal
  matrix:
    - RAKU_VERSION=daily
    - RAKU_VERSION=2019.11
    - RAKU_VERSION=2020.01


before_install:
  - docker build -t ${USER}/rakudo:${RAKU_VERSION} ${RAKU_VERSION}
  

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ${USER}/rakudo:${RAKU_VERSION}